[package]
name = "kopis_kem"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
license = "MIT/Apache-2.0"
version = "0.1.0"
edition = "2021"
keywords = ["cryptography", "crypto", "post-quantum", "encapsulation", "kem"]
categories = ["cryptography", "no-std"]

[dependencies]
rand_core = "0.9"
turboshake = { version = "0.7", default-features = false }
subtle = { version = "2.6", default-features = false, features = [
    "const-generics",
] }
zeroize = { version = "1", default-features = false, features = ["derive"] }

[dev-dependencies]
rand = "0.9"
criterion = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = { version = "0.4", features = ["serde"] }
libcrux-ml-kem = { version = "=0.0.10", features = ["mlkem512", "mlkem768", "mlkem1024"] }
graviola = "=0.4.1"

[[bench]]
name = "all"
harness = false
